all:
	g++ -lm -o receive receive.cpp RF24/*.o RF24Network/*.o

debug:
	g++ -DDEBUG -lm -o receive receive.cpp RF24/*.o RF24Network/*.o
	
verbose:
	g++ -DVERBOSE -lm -o receive receive.cpp RF24/*.o RF24Network/*.o
